import Bloog from "../components/Bloog/Blog";
import HealthyHero from "../components/Healthy/Health";
export const metadata = {
  title: "Blogs",
  description: "Discover the benefits of natural living with our selection of spices, beauty products, natural oils, herbal drinks, healthy herbs, and snacks & nuts. Boost your wellness, enhance your beauty, and enjoy nutritious, flavorful, and natural products every day.",
};
function Bloogs(){
    return (
        <>
        <HealthyHero desc="Discover the benefits of natural living with our selection of spices, beauty products, natural oils, herbal drinks, healthy herbs, and snacks & nuts. Boost your wellness, enhance your beauty, and enjoy nutritious, flavorful, and natural products every day." name="Explore the World of Natural Products" title="Blos"/>
        <div className="Bloogs">
              <Bloog img="./Assets/cat-5.jpg" Date="31/10/2025" Author="By Doctor VigaBank" name="Diffrent Types Of Snacks & Nuts" details="Snacks and nuts come in a wide variety of flavors and forms, offering both delicious taste and valuable nutritional benefits. Nuts such as almonds, cashews, pistachios, walnuts, hazelnuts, and peanuts are rich in healthy fats, protein, fiber, vitamins, and antioxidants. They support heart health, boost energy, improve brain function, and help keep you full for longer.Snacks also include dried fruits, granola mixes, roasted seeds, healthy chips, protein bars, and natural sweet treats. These options provide quick energy, satisfy cravings, and offer a convenient source of nutrients throughout the day."/>
              <Bloog img="./Assets/cat-1.jpg" Date="31/10/2025" Author="By Doctor VigaBank" name="How can you benefit from Beauty Products?" details="Beauty products offer a wide range of benefits that support both your appearance and overall confidence. They help nourish the skin, protect it from environmental damage, and correct common concerns such as dryness, dark spots, acne, and signs of aging. Using the right products can improve skin texture, even out skin tone, and keep the skin hydrated and healthy. Hair and body care products also strengthen, repair, and enhance natural beauty, giving you a fresh and radiant look. Whether used for daily care or special treatments, beauty products make it easier to maintain a clean, glowing, and well-groomed appearance — helping you feel confident inside and out."/>
              <Bloog img="./Assets/cat-4.jpg" Date="31/10/2025" Author="By Doctor VigaBank" name="Diffrent Types Of Natural Drinks & Benfits" details="Natural herbs and drinks such as ginger, cloves, anise, caraway, black seed, coffee, and many others provide powerful health benefits that support the body in a natural and effective way. These ingredients are rich in vitamins, minerals, and antioxidants that help boost the immune system, improve digestion, reduce inflammation, and enhance energy levels.Ginger and cloves support digestion and fight inflammation, while anise and caraway help relax the body and ease bloating. Black seed strengthens immunity and promotes overall wellness, and coffee provides natural energy and improves focus. Together, these natural ingredients help cleanse the body, support respiratory and digestive health, improve circulation, and promote a balanced and healthy lifestyle."/>           
              <Bloog img="./Assets/cat-2.jpg" Date="31/10/2025" Author="By Doctor VigaBank" name="How can you benefit from natural spices?" details="Natural spices offer a wide range of health benefits beyond adding flavor to your meals. They are rich in antioxidants, vitamins, and anti-inflammatory properties that support overall wellness. Using them regularly can help boost immunity, improve digestion, enhance metabolism, and promote healthy skin. Each spice has its own unique benefits — for example, turmeric supports joint health, ginger aids digestion, cinnamon helps balance blood sugar, and black pepper enhances nutrient absorption. Whether you use them in cooking, drinks, or herbal mixes, natural spices provide a simple and powerful way to improve your lifestyle and maintain your health naturally."/>
              <Bloog img="./Assets/cat-3.jpg" Date="31/10/2025" Author="By Doctor VigaBank" name="How can you benefit from Natural oils?" details="Natural oils provide powerful benefits for the skin, hair, and overall wellness. They are rich in vitamins, antioxidants, and essential fatty acids that deeply nourish, hydrate, and repair the body. When used on the skin, natural oils help restore moisture, reduce dryness, calm irritation, and improve elasticity — giving a smooth and radiant appearance. For hair, they strengthen the roots, reduce hair fall, promote growth, and add natural shine. Many natural oils also support relaxation, reduce stress, and improve sleep when used for massage or aromatherapy. Whether applied directly, mixed with skincare routines, or used in hair treatments, natural oils offer a gentle and effective way to enhance beauty and maintain long-lasting health."/>
        </div>
        </>
    )
}
export default Bloogs;